[alias]
cov = ["tarpaulin", "--ignore-tests", "--tests", "--doc", "--out", "Lcov"]
d = ["doc", "--no-deps"]
html = ["tarpaulin", "--ignore-tests", "--tests", "--doc", "--out", "html"]
td = ["test", "--doc"]
