mod cie_jch;
mod cie_lab;
mod cie_lch;
mod cie_xyy;
mod cie_xyz;
mod curve_segment;
mod data;
mod date_time_number;
mod encoded_xyz_number;
mod icc_header;
mod matrix;
mod mlu;
mod named_color_list;
mod pipeline;
mod profile;
mod profile_id;
mod seq;
mod signature;
mod tag_entry;
mod tone_curve;
mod vector;

pub use cie_jch::CIEJCh;
pub use cie_lab::CIELab;
pub use cie_lch::CIELCh;
pub use cie_xyy::CIExyY;
pub use cie_xyy::CIExyYTriple;
pub use cie_xyz::CIEXYZ;
pub use curve_segment::CurveSegment;
pub use data::ICCData;
pub use date_time_number::DateTimeNumber;
pub use encoded_xyz_number::EncodedXYZNumber;
pub use icc_header::ICCHeader;
pub use matrix::Matrix;
pub use mlu::Mlu;
pub use mlu::MluEntry;
pub use named_color_list::NamedColor;
pub use named_color_list::NamedColorList;
pub use pipeline::Pipeline;
pub use pipeline::PipelineEvalFn;
pub use pipeline::stage::Stage;
pub use pipeline::stage::StageClutData;
pub use pipeline::stage::StageData;
pub use pipeline::stage::StageEvalFn;
pub use pipeline::StageLoc;
pub use pipeline::stage::StageMatrixData;
pub use pipeline::stage::StageToneCurveData;
pub use profile::Profile;
pub use profile_id::ProfileID;
pub use seq::Sequence;
pub use seq::SequenceDescriptor;
pub use signature::Signature;
pub use tag_entry::TagEntry;
pub use tone_curve::ToneCurve;
pub use tone_curve::ToneCurveSegment;
pub use vector::Vec3;

#[allow(missing_docs)]
pub mod signatures;

pub const MAX_TABLE_TAG: usize = 100;
pub const MAX_CHANNELS: usize = 16;
